site_name: Nevernote
theme: readthedocs

pages:
- Home: "index.md"
- Zweite Seite: "secondpage.md"

markdown_extensions:
- footnotes
- smarty:
    smart_quotes: False

repo_url: https://github.com/kantel/cognitiones

site_dir: "/Applications/MAMP/htdocs/nevernote"

extra_css: [css/user.css]
